export const triggerPrint = (title: string, subtitle?: string) => {
  // Inject custom header and footer for print
  const printHeader = document.createElement('div');
  printHeader.className = 'print-page-header';
  printHeader.innerHTML = `
    <div style="display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 20px;">
      <div>
        <h1 style="font-size: 24px; font-weight: 900; color: #0f172a; margin: 0;">${title}</h1>
        ${subtitle ? `<p style="font-size: 14px; color: #64748b; margin: 4px 0 0 0; font-weight: 600;">${subtitle}</p>` : ''}
      </div>
      <div style="text-align: right;">
        <p style="font-size: 12px; font-weight: 700; color: #4f46e5; margin: 0; text-transform: uppercase; letter-spacing: 1px;">Mission Selection</p>
        <p style="font-size: 10px; color: #94a3b8; margin: 4px 0 0 0;">Official Study Material</p>
      </div>
    </div>
  `;
  
  const printFooter = document.createElement('div');
  printFooter.className = 'print-page-footer';
  printFooter.innerHTML = `
    <div style="display: flex; justify-content: space-between; align-items: center; border-top: 1px solid #e2e8f0; padding-top: 10px; margin-top: 20px; font-size: 10px; color: #94a3b8; font-weight: 600;">
      <p style="margin: 0;">&copy; ${new Date().getFullYear()} Mission Selection. All rights reserved.</p>
      <p style="margin: 0;">Generated by MissionGrid AI</p>
    </div>
  `;
  
  document.body.appendChild(printHeader);
  document.body.appendChild(printFooter);
  
  window.print();
  
  // Cleanup after print dialog closes
  setTimeout(() => {
    if (document.body.contains(printHeader)) {
      document.body.removeChild(printHeader);
    }
    if (document.body.contains(printFooter)) {
      document.body.removeChild(printFooter);
    }
  }, 1000);
}
